#pragma once
#include <boost/beast.hpp>
#include <boost/asio.hpp>
#include <memory>
#include <chrono>
#include <iostream>
#include "Singleton.h"
#include <vector>
#include <thread>
#include <functional>
#include <map>
