<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Label="UserMacros">
    <GrpcRoot>D:\cppsoft\grpc\grpc</GrpcRoot>
    <GrpcBuildRoot>$(GrpcRoot)\visualpro</GrpcBuildRoot>
  </PropertyGroup>
  <PropertyGroup />
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <ClCompile>
      <AdditionalIncludeDirectories>
        $(GrpcRoot)\third_party\re2;
        $(GrpcRoot)\third_party\address_sorting\include;
        $(GrpcRoot)\third_party\abseil-cpp;
        $(GrpcRoot)\third_party\protobuf\src;
        $(GrpcRoot)\include;
        %(AdditionalIncludeDirectories)
      </AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <AdditionalLibraryDirectories>
        $(GrpcBuildRoot)\third_party\re2\Debug;
        $(GrpcBuildRoot)\third_party\abseil-cpp\absl\types\Debug;
        $(GrpcBuildRoot)\third_party\abseil-cpp\absl\synchronization\Debug;
        $(GrpcBuildRoot)\third_party\abseil-cpp\absl\status\Debug;
        $(GrpcBuildRoot)\third_party\abseil-cpp\absl\random\Debug;
        $(GrpcBuildRoot)\third_party\abseil-cpp\absl\flags\Debug;
        $(GrpcBuildRoot)\third_party\abseil-cpp\absl\debugging\Debug;
        $(GrpcBuildRoot)\third_party\abseil-cpp\absl\container\Debug;
        $(GrpcBuildRoot)\third_party\abseil-cpp\absl\hash\Debug;
        $(GrpcBuildRoot)\third_party\boringssl-with-bazel\Debug;
        $(GrpcBuildRoot)\third_party\abseil-cpp\absl\numeric\Debug;
        $(GrpcBuildRoot)\third_party\abseil-cpp\absl\time\Debug;
        $(GrpcBuildRoot)\third_party\abseil-cpp\absl\base\Debug;
        $(GrpcBuildRoot)\third_party\abseil-cpp\absl\strings\Debug;
        $(GrpcBuildRoot)\third_party\abseil-cpp\absl\profiling\Debug;
        $(GrpcBuildRoot)\third_party\protobuf\Debug;
        $(GrpcBuildRoot)\third_party\zlib\Debug;
        $(GrpcBuildRoot)\Debug;
        $(GrpcBuildRoot)\third_party\cares\cares\src\lib\Debug;
        %(AdditionalLibraryDirectories)
      </AdditionalLibraryDirectories>
      <AdditionalDependencies>
        libprotobufd.lib;
        gpr.lib;
        grpc.lib;
        grpc++.lib;
        grpc++_reflection.lib;
        address_sorting.lib;
        ws2_32.lib;
        cares.lib;
        zlibstaticd.lib;
        upb_base_lib.lib;
        upb_descriptor_lib.lib;
        upb_hash_lib.lib;
        upb_json_lib.lib;
        upb_lex_lib.lib;
        upb_mem_lib.lib;
        upb_message_lib.lib;
        upb_mini_descriptor_lib.lib;
        upb_mini_table_lib.lib;
        upb_reflection_lib.lib;
        upb_textformat_lib.lib;
        upb_wire_lib.lib;
        utf8_range_lib.lib;
        ssl.lib;
        crypto.lib;
        absl_base.lib;
        absl_city.lib;
        absl_civil_time.lib;
        absl_cord.lib;
        absl_debugging_internal.lib;
        absl_demangle_internal.lib;
        absl_examine_stack.lib;
        absl_exponential_biased.lib;
        absl_failure_signal_handler.lib;
        absl_flags_config.lib;
        absl_flags_internal.lib;
        absl_flags_marshalling.lib;
        absl_flags_parse.lib;
        absl_flags_program_name.lib;
        absl_flags_usage.lib;
        absl_flags_usage_internal.lib;
        absl_graphcycles_internal.lib;
        absl_hash.lib;
        absl_hashtablez_sampler.lib;
        absl_int128.lib;
        absl_leak_check.lib;
        absl_log_severity.lib;
        absl_malloc_internal.lib;
        absl_periodic_sampler.lib;
        absl_random_distributions.lib;
        absl_random_internal_distribution_test_util.lib;
        absl_random_internal_entropy_pool.lib;
        absl_random_internal_platform.lib;
        absl_random_internal_randen.lib;
        absl_random_internal_randen_hwaes.lib;
        absl_random_internal_randen_hwaes_impl.lib;
        absl_random_internal_randen_slow.lib;
        absl_random_internal_seed_material.lib;
        absl_random_seed_gen_exception.lib;
        absl_random_seed_sequences.lib;
        absl_raw_hash_set.lib;
        absl_raw_logging_internal.lib;
        absl_scoped_set_env.lib;
        absl_spinlock_wait.lib;
        absl_stacktrace.lib;
        absl_status.lib;
        absl_strings.lib;
        absl_strings_internal.lib;
        absl_str_format_internal.lib;
        absl_symbolize.lib;
        absl_synchronization.lib;
        absl_throw_delegate.lib;
        absl_time.lib;
        absl_time_zone.lib;
        absl_statusor.lib;
        re2.lib;
        %(AdditionalDependencies)
      </AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
</Project>
